# Generated by Django 4.1.4 on 2023-02-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_profile_date_modiefied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_modiefied',
            new_name='date_modified',
        ),
    ]
