# Generated by Django 4.1.4 on 2023-02-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preset_image',
            field=models.CharField(default='default1.jpg', max_length=50),
        ),
    ]
