# Generated by Django 4.1.4 on 2023-03-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_profile_preset_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
