# Generated by Django 4.1.4 on 2023-03-03 17:38

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_remove_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.profile')),
            ],
        ),
    ]
