# Generated by Django 4.1.4 on 2023-04-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_avatar_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
