# Generated by Django 4.1.4 on 2023-04-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_alter_avatar_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='uploaded_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
